### ISSUE TITLE
Failed to decompose NEVRA

### ISSUE THREAD

**Issue by Muddyf0x** [Lunarequest/sddm2rpm#1]
Hi i wanted to install sweet sddm and found this and tried it with the sweet.tar.xz from pling. but when i wanted to install it via: sudo rpm-ostree install /path/to/file
i get this error: error: Failed to decompose NEVRA string '/Path/sweet-1.0.0-1.noarch
is that an error on my side or a problem with the program? 
The only thing regarding NEVRA strings is this https://metacpan.org/pod/RPM::NEVRA
Regards muddy

**Comment by Lunarequest** [comment]
I am not longer on a ostree distro, so i can not reproduce. I suggest deleting and trying to recreate the rpm. And also updating dependencies

**Comment by Lunarequest** [comment]
@Muddyf0x I've update the deps could you check if this works now?

**Comment by secretmango** [comment]
There are args in the function to add a version. I get the same error, downloaded it right before.

Really awesome tool! This must be a small issue that can be fixed fast but I dont know enough about RPMs

**Comment by secretmango** [comment]
Fix found: You have to integrate a version into the RPM, there is no default version stated

```
sddm2rpm sddm-theme.tar.gz --version=1.0
```

The file must be a .tar.gz Archive, if its .zip just decompress and compress it again using Ark.

I am in the process of converting lots of Files, could they just be added to this Github repo? Would fit, as its great work! I would just send you a cloud link, afaik RPMs are pretty transparent and show you their content perfectly.

**Comment by Lunarequest** [comment]
I do not want to host any rpms of sddm themes since.
1.  the authors may not be comfortable with it
2.  they may go out of date. its is simpler to generate a spec file add a url to download a version of the sddm theme and build it on copr or obs. With copr and obs you can also automate updating the spec to latest versions

regarding the `--version` flag being required. I can't reproduce this issue. There's a very specific block to set a version if one isn't provided 
```rust
let version = matches
        .value_of("version")
        .unwrap_or("1.0.0")
        .to_owned()
        .to_string();
```
regarding the tar.gz thing. it can be any type of tar archive. I have not worked on zip support since I've never seen a sddm theme distributed as a zip(afaik you need it to be a tarball for the regular kde store).
